/**
 * dotenv 文件的安全落盘（决策 63）：`eat env pull` / `eat app env pull` 写本地 `.env` 时，
 * 判据是「这个文件是不是 eat 写的」，而不是「文件在不在」——只看在不在，只能得到「每次都问」
 * 或「每次都覆盖」，前者是噪音、后者是事故（`.env` 通常在 .gitignore 里，覆盖回不来）。
 *
 * 所以落盘内容首行固定写一条标记（照 wrangler 的 "Generated by Wrangler" 与 vercel 的
 * CONTENTS_PREFIX）：命中标记就照常覆盖并报 key 级变化，没命中就中止让用户选出路。
 * 刻意不做交互确认——决策 26/54 已定「不做 TTY 判断」，这两条命令多半由 AI 代跑。
 */
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { diffDotenv, formatDateTime, type DotenvDiff } from '@eat/shared';

/** 标记行前缀：固定 ASCII，后面的中文说明怎么改都不影响判据 */
export const EAT_MARKER = '# Generated by eat';
/** 0.5.20 及以前 `eat env pull` 写的头（`app env pull` 那时根本不写头，认不出来） */
const LEGACY_MARKER = '# 由 eat env pull ';
const NOTICE = '# 值受平台审计，请勿提交到代码仓库；下次 pull 会整体覆盖本文件，手写内容请另存';

/** 落盘内容的头两行：第一行是判据，第二行是给人看的 */
export function buildHeader(command: string): string {
  return `${EAT_MARKER} — ${command} @ ${formatDateTime(new Date())}\n${NOTICE}\n`;
}

/** 去掉 eat 写的头：pull → push 往返时不能把标记回写到平台，否则每来回一次就多积一层 */
export function stripEatHeader(text: string): string {
  const lines = text.split(/\r?\n/);
  const first = lines[0] ?? '';
  if (!first.startsWith(EAT_MARKER) && !first.startsWith(LEGACY_MARKER)) return text;
  let i = 1;
  if ((lines[i] ?? '').startsWith('# 值受平台审计')) i++;
  return lines.slice(i).join('\n');
}

/** 只读文件开头，别为了判一行把几十 MB 的文件读进来（vercel 也是只读 prefix 那么长） */
function readFirstLine(file: string): string | undefined {
  let fd: number;
  try {
    fd = fs.openSync(file, 'r');
  } catch {
    return undefined; // 不存在 / 读不了，都按「没有这个文件」处理，写入时自然会再报错
  }
  try {
    const buf = Buffer.alloc(512);
    const n = fs.readSync(fd, buf, 0, buf.length, 0);
    const head = buf.subarray(0, n).toString('utf8');
    const nl = head.indexOf('\n');
    return nl >= 0 ? head.slice(0, nl) : head;
  } finally {
    fs.closeSync(fd);
  }
}

/** 文件存在且首行是 eat 的标记（含旧版的） */
export function isEatGenerated(file: string): boolean {
  const first = readFirstLine(file);
  if (first === undefined) return false;
  return first.startsWith(EAT_MARKER) || first.startsWith(LEGACY_MARKER);
}

function backupSuffix(d = new Date()): string {
  const p = (n: number): string => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

/** 目标文件是否已被 git 忽略；不在 git 仓库里 / 没有 git 命令时回 null（不下结论） */
function gitIgnored(file: string): boolean | null {
  const r = spawnSync('git', ['check-ignore', '-q', '--', path.basename(file)], {
    cwd: path.dirname(file),
    stdio: 'ignore',
  });
  if (r.error) return null;
  if (r.status === 0) return true;
  if (r.status === 1) return false;
  return null; // 128 = 不是 git 仓库
}

export interface WriteEnvOptions {
  /** 目标路径（相对路径按 cwd 解析） */
  file: string;
  /** 正文（不含头），会补上结尾换行 */
  content: string;
  /** 写进标记行，也用于拼中止时的出路命令，如 `eat env pull oss-storage` */
  command: string;
  /** 确认覆盖非 eat 生成的文件（覆盖前一定先备份） */
  force?: boolean;
}

export interface WriteEnvResult {
  /** 实际写入的绝对路径 */
  file: string;
  created: boolean;
  /** 覆盖已有文件时的 key 级变化（只有 key，不含值） */
  diff: DotenvDiff | null;
  /** --force 覆盖别人的文件时留下的备份 */
  backup: string | null;
  /** true = 没被 .gitignore 忽略，要提醒；null = 不在 git 仓库里，不提醒 */
  gitExposed: boolean | null;
}

/**
 * 写 dotenv 文件：不存在就写、是自己写过的就覆盖、是别人的就中止（`--force` 时备份后覆盖）。
 * 中止时抛错，由 index.ts 顶层统一打印并退出码 1。
 */
export function writeEnvFile(opts: WriteEnvOptions): WriteEnvResult {
  let file = path.resolve(opts.file);
  // .env 是软链时写穿到真实文件，别把软链本身换成普通文件（monorepo 里共用一份 .env 是常见做法）
  try {
    if (fs.lstatSync(file).isSymbolicLink()) file = fs.realpathSync(file);
  } catch {
    /* 不存在或悬空软链，按普通新文件处理 */
  }
  const existed = fs.existsSync(file);
  const mine = existed && isEatGenerated(file);

  if (existed && !mine && !opts.force) {
    throw new Error(
      [
        `${opts.file} 已存在，且不是 eat 生成的（首行没有 eat 标记），已中止以免覆盖你自己的文件。`,
        `  写到别处:   ${opts.command} --out ${opts.file}.eat`,
        `  只看不落盘: ${opts.command} --print`,
        `  确认要覆盖: ${opts.command} --force   （覆盖前会先备份为 ${opts.file}.bak-<时间戳>）`,
        `若这个文件本来就是 eat 早前写的（0.5.20 及以前 app env pull 不写标记），--force 覆盖一次即可，之后就带标记了。`,
      ].join('\n'),
    );
  }

  const before = existed ? fs.readFileSync(file, 'utf8') : '';
  const body = opts.content.endsWith('\n') || opts.content === '' ? opts.content : `${opts.content}\n`;
  const next = buildHeader(opts.command) + body;

  // 被 --force 覆盖掉的是用户自己的文件，而 .env 一般不在 git 里，覆盖就回不来了——先留一份。
  // eat 自己写的那些不备份：每次 pull 生一个 bak 既是噪音，也等于把密钥复制得到处都是。
  let backup: string | null = null;
  if (existed && !mine) {
    backup = `${file}.bak-${backupSuffix()}`;
    fs.copyFileSync(file, backup);
    try {
      fs.chmodSync(backup, 0o600);
    } catch {
      /* Windows 上 chmod 基本无效，忽略（决策 24） */
    }
  }

  fs.mkdirSync(path.dirname(file), { recursive: true });
  // 先写临时文件再 rename：中途失败不会留下写了一半的 .env
  const tmp = path.join(path.dirname(file), `.eat-tmp-${process.pid}-${path.basename(file)}`);
  fs.writeFileSync(tmp, next, { mode: 0o600 });
  fs.renameSync(tmp, file);
  // writeFileSync 的 mode 只在「创建」时生效：覆盖一个原来 0644 的 .env 不会收紧权限，得显式 chmod
  try {
    fs.chmodSync(file, 0o600);
  } catch {
    /* 同上 */
  }

  const ignored = gitIgnored(file);
  return {
    file,
    created: !existed,
    diff: existed ? diffDotenv(stripEatHeader(before), body) : null,
    backup,
    gitExposed: ignored === null ? null : !ignored,
  };
}

/** 两条 pull 命令共用的落盘回执：写到哪、变了什么、备份在哪、有没有暴露给 git */
export function printWriteResult(res: WriteEnvResult, summary: string): void {
  const rel = path.relative(process.cwd(), res.file) || res.file;
  console.log(`已写入 ${rel}（${summary}）`);
  if (res.backup) console.log(`  原文件已备份为 ${path.relative(process.cwd(), res.backup)}`);
  if (res.diff) {
    const { added, changed, removed } = res.diff;
    const parts = [
      added.length && `新增 ${added.join(', ')}`,
      changed.length && `修改 ${changed.join(', ')}`,
      removed.length && `删除 ${removed.join(', ')}`,
    ].filter(Boolean);
    console.log(parts.length ? `  变化：${parts.join('；')}` : '  内容无变化');
  }
  if (res.gitExposed) {
    console.log(`  ⚠ ${rel} 没有被 .gitignore 忽略，含密钥的文件别提交上去（在 .gitignore 里加一行 ${path.basename(res.file)}）`);
  }
}
